
# -*- coding: utf-8 -*-
'''
    File name: highly_divisible_triangular_number\solution__12.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #12 :: Highly divisible triangular number
# 
# For more information see:
# https://projecteuler.net/problem=12

# Problem Statement 
'''
b'The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:\n1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\nLet us list the factors of the first seven triangle numbers:\n\xc2\xa01: 1\xc2\xa03: 1,3\xc2\xa06: 1,2,3,610: 1,2,5,1015: 1,3,5,1521: 1,3,7,2128: 1,2,4,7,14,28\nWe can see that 28 is the first triangle number to have over five divisors.\nWhat is the value of the first triangle number to have over five hundred divisors?'
'''

# Solution 

# Solution Approach 
'''
'''
