
# -*- coding: utf-8 -*-
'''
    File name: an_enormous_factorial\solution__288.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #288 :: An enormous factorial
# 
# For more information see:
# https://projecteuler.net/problem=288

# Problem Statement 
'''
b'For any prime p the number N(p,q) is defined by\nN(p,q) = \xe2\x88\x91n=0 to q Tn*pn with Tn generated by the following random number generator:\n\nS0 = 290797\nSn+1 = Sn2 mod 50515093\nTn = Sn mod p\n\n\nLet Nfac(p,q) be the factorial of N(p,q).\nLet NF(p,q) be the number of factors p in Nfac(p,q).\n\n\nYou are given that NF(3,10000) mod 320=624955285.\n\n\nFind NF(61,107) mod 6110'
'''

# Solution 

# Solution Approach 
'''
'''
