
# -*- coding: utf-8 -*-
'''
    File name: distinct_powers\solution__29.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #29 :: Distinct powers
# 
# For more information see:
# https://projecteuler.net/problem=29

# Problem Statement 
'''
b'Consider all integer combinations of ab for 2 \xe2\x89\xa4 a \xe2\x89\xa4 5 and 2 \xe2\x89\xa4 b \xe2\x89\xa4 5:\n22=4, 23=8, 24=16, 25=32\n32=9, 33=27, 34=81, 35=243\n42=16, 43=64, 44=256, 45=1024\n52=25, 53=125, 54=625, 55=3125\nIf they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:\n4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125\nHow many distinct terms are in the sequence generated by ab for 2 \xe2\x89\xa4 a \xe2\x89\xa4 100 and 2 \xe2\x89\xa4 b \xe2\x89\xa4 100?'
'''

# Solution 

# Solution Approach 
'''
'''
