
# -*- coding: utf-8 -*-
'''
    File name: zeckendorf_representation\solution__297.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #297 :: Zeckendorf Representation
# 
# For more information see:
# https://projecteuler.net/problem=297

# Problem Statement 
'''
b'Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nStarting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.\n\nEvery positive integer can be uniquely written as a sum of nonconsecutive terms of the Fibonacci sequence. For example, 100 = 3 + 8 + 89.\nSuch a sum is called the Zeckendorf representation of the number.\n\nFor any integer n>0, let z(n) be the number of terms in the Zeckendorf representation of n.\nThus, z(5)\xe2\x80\x89=\xe2\x80\x891, z(14)\xe2\x80\x89=\xe2\x80\x892, z(100)\xe2\x80\x89=\xe2\x80\x893 etc.\nAlso, for 0<n<106, \xe2\x88\x91\xe2\x80\x89z(n)\xe2\x80\x89=\xe2\x80\x897894453.\n\nFind \xe2\x88\x91\xe2\x80\x89z(n) for 0<n<1017.'
'''

# Solution 

# Solution Approach 
'''
'''
