
# -*- coding: utf-8 -*-
'''
    File name: even_fibonacci_numbers\solution__even_fibonacci_numbers.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #2 :: Even Fibonacci numbers
# 
# For more information see:
# https://projecteuler.net/problem=2

# Problem Statement 
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# Solution 

# Solution Approach 
'''
'''
