
# -*- coding: utf-8 -*-
'''
    File name: optimum_polynomial\solution__101.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #101 :: Optimum polynomial
# 
# For more information see:
# https://projecteuler.net/problem=101

# Problem Statement 
'''
b'If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.\nAs an example, let us consider the sequence of cube numbers. This is defined by the generating function, un = n3: 1, 8, 27, 64, 125, 216, ...\nSuppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.\nWe shall define OP(k, n) to be the nth term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that OP(k, n) will accurately generate the terms of the sequence for n \xe2\x89\xa4 k, and potentially the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call it a bad OP (BOP).\nAs a basis, if we were only given the first term of sequence, it would be most sensible to assume constancy; that is, for n \xe2\x89\xa5 2, OP(1, n) = u1.\nHence we obtain the following OPs for the cubic sequence:\n\nOP(1, n) = 1\n1, 1, 1, 1, ...\nOP(2, n) = 7n\xe2\x88\x926\n1, 8, 15, ...\nOP(3, n) = 6n2\xe2\x88\x9211n+6\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\n1, 8, 27, 58, ...\nOP(4, n) = n3\n1, 8, 27, 64, 125, ...\n\nClearly no BOPs exist for k \xe2\x89\xa5 4.\nBy considering the sum of FITs generated by the BOPs (indicated in red above), we obtain 1 + 15 + 58 = 74.\nConsider the following tenth degree polynomial generating function:\nun = 1 \xe2\x88\x92 n + n2 \xe2\x88\x92 n3 + n4 \xe2\x88\x92 n5 + n6 \xe2\x88\x92 n7 + n8 \xe2\x88\x92 n9 + n10\nFind the sum of FITs for the BOPs.'
'''

# Solution 

# Solution Approach 
'''
'''
