
# -*- coding: utf-8 -*-
'''
    File name: pentagon_numbers\solution__44.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #44 :: Pentagon numbers
# 
# For more information see:
# https://projecteuler.net/problem=44

# Problem Statement 
'''
b'Pentagonal numbers are generated by the formula, Pn=n(3n\xe2\x88\x921)/2. The first ten pentagonal numbers are:\n1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...\nIt can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 \xe2\x88\x92 22 = 48, is not pentagonal.\nFind the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk \xe2\x88\x92 Pj| is minimised; what is the value of D?'
'''

# Solution 

# Solution Approach 
'''
'''
