
# -*- coding: utf-8 -*-
'''
    File name: cyclical_figurate_numbers\solution__61.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #61 :: Cyclical figurate numbers
# 
# For more information see:
# https://projecteuler.net/problem=61

# Problem Statement 
'''
b'Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:\nTriangle\n\xc2\xa0\nP3,n=n(n+1)/2\n\xc2\xa0\n1, 3, 6, 10, 15, ...\nSquare\n\xc2\xa0\nP4,n=n2\n\xc2\xa0\n1, 4, 9, 16, 25, ...\nPentagonal\n\xc2\xa0\nP5,n=n(3n\xe2\x88\x921)/2\n\xc2\xa0\n1, 5, 12, 22, 35, ...\nHexagonal\n\xc2\xa0\nP6,n=n(2n\xe2\x88\x921)\n\xc2\xa0\n1, 6, 15, 28, 45, ...\nHeptagonal\n\xc2\xa0\nP7,n=n(5n\xe2\x88\x923)/2\n\xc2\xa0\n1, 7, 18, 34, 55, ...\nOctagonal\n\xc2\xa0\nP8,n=n(3n\xe2\x88\x922)\n\xc2\xa0\n1, 8, 21, 40, 65, ...\nThe ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.\nThe set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).\nEach polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.\nThis is the only set of 4-digit numbers with this property.\nFind the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.'
'''

# Solution 

# Solution Approach 
'''
'''
