
# -*- coding: utf-8 -*-
'''
    File name: pythagorean_tree\solution__395.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #395 :: Pythagorean tree
# 
# For more information see:
# https://projecteuler.net/problem=395

# Problem Statement 
'''
b"The Pythagorean tree is a fractal generated by the following procedure:\n\n\n\nStart with a unit square. Then, calling one of the sides its base (in the animation, the bottom side is the base):\n Attach a right triangle to the side opposite the base, with the hypotenuse coinciding with that side and with the sides in a 3-4-5 ratio. Note that the smaller side of the triangle must be on the 'right' side with respect to the base (see animation).\n Attach a square to each leg of the right triangle, with one of its sides coinciding with that leg.\n Repeat this procedure for both squares, considering as their bases the sides touching the triangle.\n\nThe resulting figure, after an infinite number of iterations, is the Pythagorean tree.\n\n\n\n\n\nIt can be shown that there exists at least one rectangle, whose sides are parallel to the largest square of the Pythagorean tree, which encloses the Pythagorean tree completely.\n\n\nFind the smallest area possible for such a bounding rectangle, and give your answer rounded to 10 decimal places."
'''

# Solution 

# Solution Approach 
'''
'''
