
# -*- coding: utf-8 -*-
'''
    File name: code\triangular_pentagonal_and_hexagonal\sol_45.py
    Author: Vaidic Joshi
    Date created: Oct 20, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #45 :: Triangular, pentagonal, and hexagonal
# 
# For more information see:
# https://projecteuler.net/problem=45

# Problem Statement 
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle
 
Tn=n(n+1)/2
 
1, 3, 6, 10, 15, ...
Pentagonal
 
Pn=n(3n−1)/2
 
1, 5, 12, 22, 35, ...
Hexagonal
 
Hn=n(2n−1)
 
1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
'''

# Solution 

# Solution Approach 
'''
'''
