
# -*- coding: utf-8 -*-
'''
    File name: triangular_pentagonal_and_hexagonal\solution__45.py
    Author: Vaidic Joshi
    Date created: Oct 18, 2018
    Python Version: 3.x
'''

# Solution to Project Euler Problem #45 :: Triangular, pentagonal, and hexagonal
# 
# For more information see:
# https://projecteuler.net/problem=45

# Problem Statement 
'''
b'Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:\nTriangle\n\xc2\xa0\nTn=n(n+1)/2\n\xc2\xa0\n1, 3, 6, 10, 15, ...\nPentagonal\n\xc2\xa0\nPn=n(3n\xe2\x88\x921)/2\n\xc2\xa0\n1, 5, 12, 22, 35, ...\nHexagonal\n\xc2\xa0\nHn=n(2n\xe2\x88\x921)\n\xc2\xa0\n1, 6, 15, 28, 45, ...\nIt can be verified that T285 = P165 = H143 = 40755.\nFind the next triangle number that is also pentagonal and hexagonal.'
'''

# Solution 

# Solution Approach 
'''
'''
